### ISSUE TITLE
test out citp search study analysis environment

### ISSUE THREAD

**Issue by betling** [mozilla-rally/search-engine-usage-study#93]

**Comment by betling** [comment]
the environment is there and I can create a notebook but don't see any data --  even demographics and enrollment.  need to check with engineering to see if something else needs to be done to get this data ported over or if we just wait for app to get approved.

**Comment by betling** [comment]
I don't seem to be able to assign this issue to myself

**Comment by betling** [comment]
okay, so kart should be able to test it out then.  my confusion for the search study and demographics tables is that it is a study you can sign up for after enrolling in rally, but I guess what you are saying here is that right now the only thing that study is doing is launching an external qualtrics survey.  that makes more sense now.  thanks.

**Comment by rhelmer** [comment]
The enrollment and demographics pings are sent by the core add-on and go to these namespaces:

- `rally-core/demographics`
- `rally-core/study-enrollment`
- `rally-core/study-unenrollment`

In the past, we've always set up the environment before launch the study, so I'm not sure if these are hooked up correctly or not.

We've had studies also send a redundant enrollment ping to their own environment, but we decided to move away from in favor of the `rally-core` ones (which will continue to be the case for the rally web platform). Since the environment wasn't set up yet any pings sent directly from the extension wouldn't be processed (but as I mentioned above the `rally-core` environment should be the ones that matter).
